routes/web.php
Auth::routes();



Route::get('/', 'HomeController@index')->name('home')->middleware('validWebSite');


Route::get('lang/{language}', 'LanguageController@switchLang')->name('lang.switch');
    
    Route::group(['prefix' => 'administrator'], function () {


        Route::get('/login', 'Admin\LoginController@login')->name('admin.login');
        Route::post('/login', 'Admin\LoginController@postLogin')->name('admin.postLogin');
        
        // Password Reset Routes...
        
        Route::get('password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('administrator.password.request');
        Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('administrator.password.email');
        Route::get('password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('administrator.password.reset.token');
        Route::post('password/reset', 'Admin\Auth\ResetPasswordController@reset');
        
    });
    
    Route::group(['prefix' => 'administrator', 'middleware' => ['admin']], function () {
        
        Route::get('/', 'Admin\HomeController@index')->name('home');
        Route::get('/home', 'Admin\HomeController@index')->name('admin.home');
    
    
        // administrators --- Admin Panel users
        // add admin or some one who controll Or help for admin panel
    
        Route::resource('helpAdmin', 'Admin\HelpAdminController');
        Route::get('helpAdmin/{id}/delete', 'Admin\HelpAdminController@delete')->name('helpAdmin.delete');
        Route::post('helpAdmin/{id}/delete', 'Admin\HelpAdminController@deleteHelpAdmin')->name('helpAdmin.message.delete');
        Route::post('helpAdmin/{id}/suspend', 'Admin\HelpAdminController@suspendHelpAdmin')->name('helpAdmin.message.suspend');
        Route::get('user/{id}/delete', 'Admin\UsersController@delete')->name('user.for.delete');
        Route::post('user/suspend', 'Admin\HelpAdminController@suspend')->name('user.suspend');
        // Roles routes ..........
        Route::resource('roles', 'Admin\RolesController');
        Route::post('role/delete', 'Admin\RolesController@delete')->name('role.delete');
    
    
        Route::resource('users', 'Admin\UsersController');
        Route::post('accepted','Admin\UsersController@accpetedUser')->name('user.accepted');
    
        Route::get('settings/aboutus', 'Admin\SettingsController@aboutus')->name('settings.aboutus');
        Route::get('settings/taxs', 'Admin\SettingsController@taxs')->name('settings.taxs');
        Route::get('settings/terms', 'Admin\SettingsController@terms')->name('settings.terms');
        Route::get('settings/suspendElement', 'Admin\SettingsController@suspendElement')->name('settings.suspendElement');

//        Route::resource('faqs', 'Admin\FaqsController');

        Route::get('/settings/app-general-settings', 'Admin\SettingsController@appGeneralSettings')->name('settings.app.general');
        Route::get('settings/contacts', 'Admin\SettingsController@contactus')->name('settings.contactus');


        Route::post('/settings', 'Admin\SettingsController@store')->name('administrator.settings.store');
    
        Route::post('contactus/reply/{id}', 'Admin\SupportsController@reply')->name('support.reply');
        Route::get('contactus', 'Admin\SupportsController@index')->name('support.index');
        Route::get('contactus/{id}', 'Admin\SupportsController@show')->name('support.show');
        Route::post('support/contact/delete', 'Admin\SupportsController@delete')->name('support.contact.delete');


        Route::resource('supports', 'Admin\SupportsController');
        Route::post('supports/delete', 'Admin\SupportsController@delete')->name('supports.delete');

        Route::resource('types', 'Admin\TypesSupportController');


//        Route::get('public/notifications', 'Admin\NotificationsController@publicNotifications')->name('public.notifications');
//        Route::get('public/notifications/create', 'Admin\NotificationsController@createPublicNotifications')->name('create.public.notifications');


        Route::post('city/delete/group', 'Admin\CitiesController@groupDelete')->name('cities.group.delete');
        Route::post('cities/delete', 'Admin\CitiesController@delete')->name('city.delete');
        Route::resource('cities', 'Admin\CitiesController');
        Route::post('city/suspend', 'Admin\CitiesController@suspend')->name('city.suspend');

        // -------------------------------------- categories .................
        Route::resource('categories', 'Admin\CategoriesController');
        Route::post('categories/delete', 'Admin\CategoriesController@delete')->name('categories.delete');
        Route::post('categories/suspend', 'Admin\CategoriesController@suspend')->name('categories.suspend');

        // -------------------------------------- brands .................
        Route::resource('brands', 'Admin\BrandController');
        Route::post('brands/delete', 'Admin\BrandController@delete')->name('brands.delete');
        Route::post('brands/suspend', 'Admin\BrandController@suspend')->name('brands.suspend');

        // -------------------------------------- sizes .................
        Route::resource('sizes', 'Admin\SizeController');
        Route::post('sizes/delete', 'Admin\SizeController@delete')->name('sizes.delete');


        // -------------------------------------- currencies .................
        Route::resource('currencies', 'Admin\CurrencyController');
        Route::post('currencies/delete', 'Admin\CurrencyController@delete')->name('currencies.delete');


        // -------------------------------------- colors .................
        Route::resource('colors', 'Admin\ColorController');
        Route::post('colors/delete', 'Admin\ColorController@delete')->name('colors.delete');



        // -------------------------------------- purchaseTypes .................
        Route::resource('purchaseTypes', 'Admin\purchaseTypesController');
        Route::post('purchaseTypes/delete', 'Admin\purchaseTypesController@delete')->name('purchaseTypes.delete');

        // -------------------------------------- purchaseTypes .................
        Route::resource('dealDays', 'Admin\DealOfDaysController');
        Route::post('dealDays/delete', 'Admin\DealOfDaysController@delete')->name('dealDays.delete');



        // -------------------------------------- products .................
        Route::resource('products', 'Admin\ProductsController');
        Route::post('products/delete', 'Admin\ProductsController@delete')->name('products.delete');
        Route::post('products/suspend', 'Admin\ProductsController@suspend')->name('products.suspend');


        Route::resource('reports', 'Admin\ReportsController');
        
        Route::post('/logout', 'Admin\LoginController@logout')->name('administrator.logout');
        
    });



Route::get('/sub', function (Illuminate\Http\Request $request) {

    $cities =\App\Models\City::whereParentId($request->id)->get();

    if (!empty($cities) && count($cities) > 0){
        return response()->json( $cities);
    }else{

        return response()->json(401);
    }


})->name('getSub');



Route::group([
    'namespace' => 'Site',
    'middleware' => 'localeControlPanel',
], function () {

    Route::group(['prefix' => 'Auth','namespace' => 'Auth'], function () {

        Route::get('/registerSite','RegisterController@index')->name('site.get.register');
        Route::get('/loginSite','LoginController@index')->name('site.get.login');

        Route::get('/resetEmail','ResetController@resetEmail')->name('site.resetEmail');
        Route::get('/updatePassword','ResetController@updatePassword')->name('site.updatePassword');

        Route::post('/registerAccount','RegisterController@register')->name('site.registerSite');
        Route::post('/LoginSite','LoginController@login')->name('site.login');

        Route::post('/resetEmail','ResetController@sendMail')->name('site.sendMail');
        Route::post('/updatePassword','ResetController@updatePass')->name('site.updatePass');

        Route::post('/logOutSite','LoginController@logOut')->name('site.logOut');


    });

    Route::group(['prefix' => 'products' ], function () {

        Route::get('/','ProductsController@index')->name('site.getAllProducts');
        Route::get('/show','ProductsController@show')->name('site.product.show');

    });

    Route::group(['prefix' => 'searchSite' ], function () {

        Route::get('/','SearchController@search')->name('site.search');

    });

    Route::group(['middleware' => 'validWebSite'], function () {


        Route::resource('usersSite', 'UsersController');

        Route::get('/editAddress','UsersController@editAddress')->name('site.editAddress');
        Route::get('/listFavourite','UsersController@listFavourite')->name('site.listFavourite');
        Route::post('/addAddress','UsersController@addAddress')->name('site.user.addAddress');


        Route::resource('cartSite', 'CartController');
        Route::post('/cart/delete','CartController@delete')->name('site.cart.delete');

        Route::group(['prefix' => 'ordersSite' ], function () {

            Route::get('/','OrderController@index')->name('site.getAllOrders');
            Route::post('/storeOrder','OrderController@storeOrder')->name('site.storeOrder');

        });

    });


    Route::post('/makeFavourite','UsersController@makeFavourite')->name('site.user.makeFavourite');

    Route::group(['prefix' => 'setting'], function () {

        Route::get('/SiteAbout','SettingController@aboutUs')->name('site.aboutUs');
        Route::get('/SitePrivacy','SettingController@Privacy')->name('site.privacy');
        Route::get('/SiteContact','SettingController@contactUsIndex')->name('site.contactUs');
        Route::post('/SiteContact','SettingController@contactUs')->name('site.contactUs');

    });

    Route::get('/','indexController@index')->name('firstPageSite');


});

resources/views/admin/sizes/create.blade.php
@extends('admin.layouts.master')
@section('title', __('maincp.users_manager'))


@section('styles')



@endsection
@section('content')



    <form method="POST" action="{{ route('sizes.store') }}" enctype="multipart/form-data"
          data-parsley-validate novalidate>
    {{ csrf_field() }}

    <!-- Page-Title -->
        <div class="row">
            <div class="col-lg-12  ">
                <div class="btn-group pull-right m-t-15">
                    <button type="button" class="btn btn-custom  waves-effect waves-light"
                            onclick="window.history.back();return false;"> رجوع <span class="m-l-5"><i
                                    class="fa fa-reply"></i></span>
                    </button>
                </div>
                <h4 class="page-title">إدارة {{$pageName}}</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12  ">
                <div class="card-box">


                    <h4 class="header-title m-t-0 m-b-30"> إضافة {{$pageName}}</h4>

                    <div class="row">

                        @if(request('type'))
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="userName">إسم القسم الرئيسي*</label>
                                    <select name="parentId" id="" class="form-control requiredFieldWithMaxLenght" required>
                                        <option value="" selected disabled=""> إختر القسم</option>
                                        @foreach($cats as $value)
                                            <option value="{{ $value->id }}">{{ $value->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        @endif


                        <div class="col-xs-6">
                            <div class="form-group">
                                <label for="userName"> {{$pageName}}   باللغة العربية</label>
                                <input type="text" name="name_ar"
                                       class="form-control requiredFieldWithMaxLenght"
                                       required
                                       placeholder="   باللغة العربية{{$pageName}}  ..."/>
                                <p class="help-block" id="error_userName"></p>
                                @if($errors->has('name_ar'))
                                    <p class="help-block">
                                        {{ $errors->first('name_ar') }}
                                    </p>
                                @endif
                            </div>
                        </div>

                        <div class="col-xs-6">
                            <div class="form-group">
                                <label for="userName"> {{$pageName}}   باللغة الإنجليزية</label>
                                <input type="text" name="name_en"
                                       class="form-control requiredFieldWithMaxLenght"
                                       required
                                       placeholder="   باللغة الإنجليزية {{$pageName}}  ..."/>
                                <p class="help-block" id="error_userName"></p>
                                @if($errors->has('name_en'))
                                    <p class="help-block">
                                        {{ $errors->first('name_en') }}
                                    </p>
                                @endif
                            </div>
                        </div>

                        {{--<div class="col-xs-6">--}}
                            {{--<div class="form-group">--}}
                                {{--<label for="usernames">صورة القسم  *</label>--}}
                                {{--<input type="file" name="image" class="dropify" data-max-file-size="6M"/>--}}
                            {{--</div>--}}

                        {{--</div>--}}



                    </div>


                    <div class="form-group text-right m-t-20">
                        <button class="btn btn-warning waves-effect waves-light m-t-20" type="submit">
                            @lang('maincp.save_data')
                        </button>
                        <button onclick="window.history.back();return false;" type="reset"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20">
                            @lang('maincp.disable')
                        </button>
                    </div>

                </div>
            </div><!-- end col -->


        </div>
        <!-- end row -->
    </form>

@endsection



@section('scripts')
    <script type="text/javascript"
            src="{{ request()->root() }}/public/assets/admin/js/validate-{{ config('app.locale') }}.js"></script>
    <script type="text/javascript">

        $('form').on('submit', function (e) {

            e.preventDefault();

            var formData = new FormData(this);

            var form = $(this);
            form.parsley().validate();

            if (form.parsley().isValid()){
                $('.loading').show();

                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        $('.loading').hide();
                        // $('form').trigger("reset");
                        console.log(data);

                        var shortCutFunction = 'success';
                        var msg = data.message;
                        var title = 'نجاح';
                        toastr.options = {
                            positionClass: 'toast-top-left',
                            onclick: null
                        };
                        var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                        $toastlast = $toast;
                        setTimeout(function () {
                            window.location.href = data.url;
                        }, 2000);
                    },
                    error: function (data) {
                    }
                });
            }else {
                $('.loading').hide();
            }
        });

    </script>
@endsection

resources/views/admin/sizes/edit.blade.php
@extends('admin.layouts.master')
@section('title', __('maincp.users_manager'))


@section('styles')



@endsection
@section('content')


    <form method="POST" action="{{ route('sizes.update', $brand->id) }}" enctype="multipart/form-data"
          data-parsley-validate novalidate>
    {{ csrf_field() }}
    {{ method_field('PUT') }}


    <!-- Page-Title -->
        <div class="row">
            <div class="col-lg-12 ">
                <div class="btn-group pull-right m-t-15">
                    <button type="button" class="btn btn-custom  waves-effect waves-light"
                            onclick="window.history.back();return false;"> رجوع <span class="m-l-5"><i
                                    class="fa fa-reply"></i></span>
                    </button>
                </div>
                <h4 class="page-title">إسم {{$pageName}}</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12 ">
                <div class="card-box">


                    <h4 class="header-title m-t-0 m-b-30">تعديل {{$pageName}}</h4>

                    <div class="row">



                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="userName"> {{$pageName}}   باللغة العربية</label>
                                    <input type="text" name="name_ar"
                                           class="form-control requiredFieldWithMaxLenght"
                                           required value="{{optional($brand->translate('ar'))->name}}"
                                           placeholder="   باللغة العربية{{$pageName}}  ..."/>
                                    <p class="help-block" id="error_userName"></p>
                                    @if($errors->has('name_ar'))
                                        <p class="help-block">
                                            {{ $errors->first('name_ar') }}
                                        </p>
                                    @endif
                                </div>
                            </div>

                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="userName"> {{$pageName}}   باللغة الإنجليزية</label>
                                    <input type="text" name="name_en" value="{{optional($brand->translate('en'))->name}}"
                                           class="form-control requiredFieldWithMaxLenght"
                                           required
                                           placeholder="   باللغة الإنجليزية {{$pageName}}  ..."/>
                                    <p class="help-block" id="error_userName"></p>
                                    @if($errors->has('name_en'))
                                        <p class="help-block">
                                            {{ $errors->first('name_en') }}
                                        </p>
                                    @endif
                                </div>
                            </div>







                        <!-- end col -->
                    </div>


                    <div class="form-group text-right m-t-20">
                        <button class="btn btn-warning waves-effect waves-light m-t-20" type="submit">
                            @lang('maincp.save_data')
                        </button>
                        <button onclick="window.history.back();return false;" type="reset"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20">
                            @lang('maincp.disable')
                        </button>
                    </div>

                </div>
            </div><!-- end col -->


        </div>
        <!-- end row -->
    </form>

@endsection



@section('scripts')

    <script type="text/javascript"
            src="{{ request()->root() }}/public/assets/admin/js/validate-{{ config('app.locale') }}.js"></script>

    <script type="text/javascript">

        $('form').on('submit', function (e) {

            e.preventDefault();

            var formData = new FormData(this);

            var form = $(this);

            form.parsley().validate();

            if (form.parsley().isValid()){
                $('.loading').show();

                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        $('.loading').hide();

                        // $('form').trigger("reset");

                        var shortCutFunction = 'success';
                        var msg = data.message;
                        var title = 'نجاح';
                        toastr.options = {
                            positionClass: 'toast-top-left',
                            onclick: null
                        };
                        var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                        $toastlast = $toast;
                        setTimeout(function () {


                            window.location.href = data.url;
                        }, 2000);
                    },
                    error: function (data) {

                    }
                });

            }


        });

    </script>
@endsection

resources/views/admin/sizes/index.blade.php
@extends('admin.layouts.master')

@section('title', __('maincp.cities'))

@section('content')


    <!-- Page-Title -->
    <div class="row">
        <div class="col-sm-12">
            <div class="btn-group pull-right m-t-15 ">
                <a href="{{ route('sizes.create') }}"
                   type="button" class="btn btn-custom waves-effect waves-light"
                   aria-expanded="false">
                <span class="m-l-5">
                <i class="fa fa-plus"></i>
                </span>
                    إضافة مقاس
                </a>
            </div>
            <h4 class="page-title">{{$pageName}} </h4>
        </div>
    </div>



    <div class="row">
        <div class="col-sm-12">
            <div class="card-box table-responsive">

                <div class="dropdown pull-right">
                    {{--<a href="#" class="dropdown-toggle card-drop" data-toggle="dropdown" aria-expanded="false">--}}
                    {{--<i class="zmdi zmdi-more-vert"></i> --}}
                    {{--</a>--}}

                </div>

                <h4 class="header-title m-t-0 m-b-30"> إدارة {{$pageName}}</h4>

                <table id="datatable-fixed-header" class="table table-striped table-bordered dt-responsive nowrap"
                       cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>اسم المقاس او الحجم </th>

                        <th>@lang('trans.options')</th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach($brands as $row)
                        <tr>

                            <td>{{ $row->name }}</td>

                            <td>

                                <a href="{{ route('sizes.edit', $row->id) }}"
                                   data-toggle="tooltip" data-placement="top"
                                   data-original-title=" تعديل"
                                   class="btn btn-icon btn-xs waves-effect  btn-info">
                                    <i class="fa fa-edit"></i>
                                </a>

                            </td>
                        </tr>
                    @endforeach

                    </tbody>
                </table>
            </div>
        </div><!-- end col -->
    </div>
    <!-- end row -->


@endsection


@section('scripts')



    <script>

        $('body').on('click', '.removeElement', function () {
            var id = $(this).attr('data-id');
            var url = $(this).attr('data-url');
            var $tr = $(this).closest($('#elementRow' + id).parent().parent());
            swal({
                title: "هل انت متأكد؟",
                text: "يمكنك استرجاع المحذوفات مرة اخرى لا تقلق.",
                type: "error",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "موافق",
                cancelButtonText: "إلغاء",
                confirmButtonClass: 'btn-danger waves-effect waves-light',
                closeOnConfirm: true,
                closeOnCancel: true,
            }, function (isConfirm) {
                if (isConfirm) {
                    $.ajax({
                        type: 'POST',
                        url: url,
                        data: {id: id},
                        dataType: 'json',
                        success: function (data) {

                            if (data.status == true) {
                                var shortCutFunction = 'success';
                                var msg = 'لقد تمت عملية الحذف بنجاح.';
                                var title = data.title;
                                toastr.options = {
                                    positionClass: 'toast-top-left',
                                    onclick: null
                                };
                                var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                                $toastlast = $toast;

                                $tr.find('td').fadeOut(1000, function () {
                                    $tr.remove();
                                });
                            }
                        }
                    });
                }
            });
        });





        $(document).ready(function () {
            //$('#datatable').dataTable();
            //$('#datatable-keytable').DataTable( { keys: true } );
            $('#datatable-responsive').DataTable();

        });


    </script>


@endsection